linking obsidian to the preact
artem-barmin/obsidian-tree-edit pull request #1
Opened 2021-11-03 20:24 UTC by kravich13

Запушил всё, что имею на данный момент по преакту (работает в обсидионе, только окно вертикальное).

2021-11-04 07:34 UTC, artem-barmin-dev requested changes
В целом качество кода хорошее, есть несколько не-принципиальных замечаний

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/components/App.tsx
> +      // const currentParentElem: id = parents[parents.length - 1];
не оставляй закоменченый код

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/components/App.tsx
> +          // Сhange the previous clicked item to the current item
аналогично

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/components/App.tsx
> +            if (elem.isChild) elem.isChild = false;
зачем эти ифы? если true - будет false, если false - останется false. Только читабельность ухудшают

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/components/App.tsx
> +          const child = children.find((child) => child.id === elem.id);
лучше используй lodash: `_.find(children, {id: elem.id})`

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/main.ts
> +// class SampleModal extends Modal {
удаляй коменты

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +    const contentHTML: string = await astToHTML(elem);
сразу в preact vdom здесь конверти, а не каждый раз при рендере компонента

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +      for (const { id, neighbors } of currentLevel) {
```
const allCurrentLevelIds = _.map(currentLevel, 'id');
_.forEach(currentLevel, lvl => (lvl.neighbors = _.difference(allCurrentLevelIds, [lvl.id])))));
```

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +      for (const chainEl of globalInput) {
не люблю вложенные циклы, можно ли переформулировать эту функцию?

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/treeEdit-view.tsx
> +      // if(this.f.length === 0 || this.getLeafTarget().view.getViewType() != 'markdown'){
удали комент, они в истории остаются энивей

2021-11-04 07:34 UTC, artem-barmin-dev commented on src/treeEdit-view.tsx
> +      // div.innerText = divContent
коменты мешают читать код

2021-11-04 15:47 UTC, artem-barmin-dev requested changes
Добавил коменты по control flow, остальное норм

2021-11-04 15:47 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +    if (elem.type === 'thematicBreak') continue;
использование continue и break сильно повышает когнитивную сложность кода т.к. создает внезапные точки обрыва control flow - выполнение становится нелинейным(https://docs.codeclimate.com/docs/cognitive-complexity#breaks-in-flow)

переделай на if, убери все `continue` и `break` из кода

2021-11-04 15:47 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +        continue;
continue

2021-11-04 15:47 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +  const tree = buildLevel(inputArr);
`return buildLevel(inputArr)` - зачем отдельная переменная?

2021-11-04 15:47 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +        if (uniqDepths.includes(depth)) return;
опять нелинейный control flow, return это лучше чем continue, но переделай на if

2021-11-08 15:02 UTC, artem-barmin-dev requested changes

2021-11-08 15:02 UTC, artem-barmin-dev commented on src/scripts/statePreactTree.ts
> +        const objTitle: IHeadersData = {
убери отдельную переменною, пуш сразу в массив

2021-12-27 21:19 UTC, artem-barmin requested changes
Есть несколько больших замечаний:
- русский текст в коде(не должно быть вобще)
- redux редьюсеры мутируют состояние(я привел пример как должно быть)
- есть несколько примеров "индусского" кода(с header и depth)

2021-12-27 21:19 UTC, artem-barmin commented on src/components/ButtonsRight.tsx
> +              title="Добавить дочку"
переделай на англ, русского в проекте быть не должно

2021-12-27 21:19 UTC, artem-barmin commented on src/components/ButtonsRight.tsx
> +  const statusTitle = isEdit ? 'Сохранить изменения' : 'Редактировать карточку';
англ везде

2021-12-27 21:19 UTC, artem-barmin commented on src/components/CardCodeMirror.tsx
> +    const chHeader = depth + 1;
разве Markdown спека гарантирует что перед хедером не может быть пробелов? я бы сделал регуляркой - позиция после последнего #(который в начале строки)

2021-12-27 21:19 UTC, artem-barmin commented on src/components/ColumnDepth.tsx
> +  }, [$divColumn, isSelectedCard]);
https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780 - разве ref можно передавать во второй аргумент useEffect?

2021-12-27 21:19 UTC, artem-barmin commented on src/redux/reducers-case-logic/rootReducer/add-card.case.ts
> +        children.splice(index, 0, { id: newCardId, depth: selectedDepth + 1 });
ты здесь и во всех остальных местах мутируешь стейт?

2021-12-27 21:19 UTC, artem-barmin commented on src/redux/reducers-case-logic/rootReducer/add-card.case.ts
> +export const addCard = (state: IStateRootReducer, { whereToAdd, markdownContent }: RootInterfaces.IAddCard) => {
слишком большая функция, разбей ее на несколько мелких которые будут вызываться, возможно какой-то код обобщи

2021-12-27 21:19 UTC, artem-barmin commented on src/redux/reducers-case-logic/rootReducer/change-card.case.ts
> +        card.isEdit = isEdit;
ну ты мутируешь старый стейт, это конечно ОК и будет работать, но это полностью наперекор практике разработки с redux

в этом примере надо было делать так:
```
{...card, isEdit, markdownContent: condition ? newContent : card.markdownContent}
```

2021-12-27 21:19 UTC, artem-barmin commented on src/redux/reducers-case-logic/rootReducer/change-card.case.ts
> +        if (newContent && (wasChanged = newContent !== card.markdownContent)) {
почему ты используешь `=` в IF? это на столько bad practice, на сколько возможно

2021-12-27 21:19 UTC, artem-barmin commented on src/redux/scripts/getReadyMarkdown.ts
> +export const getReadyMarkdown = (inputStateMDContent: IStateMDContent[]) => {
вся функция записывается в одну строку: `return _.map(inputStateMDContent, 'markdownContent').join('')`

2021-12-27 21:19 UTC, artem-barmin commented on src/redux/scripts/createCardData.ts
> +export const createEmptyHeader = (depth: number) => {
`return _.repeat('#', depth).join('')`

2021-12-27 21:19 UTC, artem-barmin commented on src/redux/scripts/createCardData.ts
> +export const createEmptyHeader = (depth: number) => {
напомнило https://shitcode.net/557

2022-02-11 16:00 UTC, artem-barmin approved these changes

2022-02-11 16:00 UTC, merged